name: Deploy Foundry Module to GitHub Pages

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq zip

      - name: Set version from tag
        id: vars
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update module.json version
        run: |
          jq '.version = "${{ steps.vars.outputs.version }}"' module.json > module.tmp && mv module.tmp module.json

      - name: Zip module
        run: |
          zip -r custom-colours-redux.zip . -x "*.git*" ".*" ".github/*"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
          allow_empty_commit: false
          keep_files: false
          enable_jekyll: false
